---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlets-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets-client
  template:
    metadata:
      labels:
        app: inlets-client
    spec:
      containers:
      - name: inlets-client
        image: inlets/inlets-pro:0.5.1
        imagePullPolicy: IfNotPresent
        command: ["inlets-pro"]
        args:
        - "client"
        - "--connect=wss://EXIT_NODE_IP:8123/connect"
        - "--tcp-ports=80,443"
        - "--token=AUTHTOKENHERE"
        - "--license=LICENSE_JWT_HERE"
---
